# Generated by Django 4.1.8 on 2023-04-10 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='beneficialownership',
            name='id',
        ),
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='id',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='affiliate_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficialownership',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('C-CORP', 'C-Corporation'), ('S-CORP', 'S-Corporation'), ('LLC', 'Limited Liability Company'), ('PARTNERSHIP', 'Partnership'), ('SOLE PROP.', 'Sole Proprietorship'), ('NON-PROFIT', 'Non-Profit Organization'), ('GOVERNMENT', 'Government Entity')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='jointly_reported',
            field=models.CharField(choices=[('JOINTLY', 'Jointly Reported'), ('SOLE', 'Solely Reported')], default='No', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='jointly_reported_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
