# Generated by Django 4.1.8 on 2023-04-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_remove_affiliate_id_remove_beneficialownership_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='affiliate_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='affiliate',
            constraint=models.UniqueConstraint(fields=('affiliate_code',), name='unique_affiliate_code'),
        ),
    ]
