# Generated by Django 4.1.8 on 2023-04-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanPage',
        ),
    ]
