from django.db import models

class SBAETRANResponse(models.Model):
    AppLoanAppNmb = models.CharField(max_length=255)
    LoanAppNm = models.CharField(max_length=255)
    LoanAppRqstAmt = models.DecimalField(max_digits=10, decimal_places=2)
    LoanAppPrtLoanNmb = models.CharField(max_length=255, blank=True)
    LoanAppPrtAppNmb = models.CharField(max_length=255, blank=True)
    LoanAppRecvDt = models.DateField(null=True, blank=True)
    LoanAppEtranEmailAdr = models.EmailField()
    LoanAppAppvDt = models.DateField(null=True, blank=True)
    LoanAppSBAAppvAmt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    LoanNmb = models.CharField(max_length=255, blank=True)
    LoanGntyFeeAmt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    LoanGntyFeeExplainTxt = models.TextField(blank=True)
    LoanGntyPercent = models.DecimalField(max_digits=6, decimal_places=3)
    LoanAppFundDt = models.DateField(null=True, blank=True)
    LoanAppStatCd = models.CharField(max_length=2)
    BusDUNSNmb = models.CharField(max_length=255)
    LiquidCreditScore = models.IntegerField()

    def __str__(self):
        return self.LoanAppNm

    class Meta:
        db_table = 'SBA_ETRAN'

class SBA7aLoanApplication(models.Model):
    # Section: Loan Application
    AgentInvolved = models.CharField(max_length=1)
    BorrowerContribAmt = models.CharField(max_length=255)
    BorrowerContribPct = models.CharField(max_length=255)
    BusinessAgeCd = models.CharField(max_length=1)
    ClosingCostAmt = models.CharField(max_length=255)
    CollateralInd = models.CharField(max_length=1)
    CurrEmpQty = models.PositiveIntegerField()
    EidlLoanNumber = models.CharField(max_length=255)
    EligPassiveCompanyInd = models.CharField(max_length=1)
    EWCPPostShipmntInd = models.CharField(max_length=255)
    EWCPSnglTransInd = models.CharField(max_length=255)
    FrnchiseCd = models.CharField(max_length=255)
    FrnchiseDeferPymtInd = models.CharField(max_length=1)
    FrnchiseDeferPymtMonths = models.CharField(max_length=255)
    FrnchiseInd = models.CharField(max_length=1)
    FrnchiseName = models.CharField(max_length=255)
    FrnchiseOpporCureInd = models.CharField(max_length=1)
    FrnchiserBooksInd = models.CharField(max_length=1)
    FrnchiseWarnTermInd = models.CharField(max_length=1)
    FullAmortPymtInd = models.CharField(max_length=1)
    FundingFeeAmt = models.CharField(max_length=255)
    GntyFeeAmt = models.CharField(max_length=255)
    InjectionInd = models.CharField(max_length=1)
    InterestStructureCd = models.CharField(max_length=1)
    JobRqmtMetInd = models.CharField(max_length=1)
    JobsCreatdQty = models.PositiveIntegerField()
    JobsRetaindQty = models.PositiveIntegerField()
    LenderAltContactCellPhn = models.CharField(max_length=255)
    LenderAltContactEmail = models.EmailField(max_length=255)
    LenderAltContactFax = models.CharField(max_length=255)
    LenderAltContactFirstNm = models.CharField(max_length=255)
    LenderAltContactInitialNm = models.CharField(max_length=255)
    LenderAltContactLastNm = models.CharField(max_length=255)
    LenderAltContactNameSuffix = models.CharField(max_length=255)
    LenderAltContactPrimPhn = models.CharField(max_length=255)
    LenderAltContactTitlTxt = models.CharField(max_length=255)
    LenderAltContactTypCd = models.CharField(max_length=255)
    LenderApplicNmb = models.CharField(max_length=255)
    LenderCntctEmail = models.EmailField(max_length=255)
    LenderCntctFax = models.CharField(max_length=255)
    LenderCntctFirstName = models.CharField(max_length=255)
    LenderCntctLastName = models.CharField(max_length=255)
    LenderCntctMiddleInitial = models.CharField(max_length=255)
    LenderCntctNameSuffix = models.CharField(max_length=255)
    LenderCntctPhnNmb = models.CharField(max_length=255)
    LenderCntctTitl = models.CharField(max_length=255)
    LenderContactCellPhn = models.CharField(max_length=255)
    LenderLoanNmb = models.CharField(max_length=255)
    LifeInsurRqmtInd = models.CharField(max_length=1)
    LimitCompensationAmt = models.CharField(max_length=255)
    LimitCompensationInd = models.CharField(max_length=1)
    LimitExemptionInd = models.CharField(max_length=1)
    LimitFixedAssetAmt = models.CharField(max_length=255)
    LimitFixedAssetInd = models.CharField(max_length=1)
    LimitLocation = models.CharField(max_length=255)
    LiquidCreditScore = models.PositiveIntegerField()
    LoanBusinessEstDt = models.DateTimeField()
    LoanExtraordinaryServFeeAmt = models.CharField(max_length=255)
    LoanExtraordinaryServFeeInd = models.CharField(max_length=1)
    LoanGrossIncomeAmt = models.CharField(max_length=255)
    LoanName = models.CharField(max_length=255)
    LoanPackagerCityName = models.CharField(max_length=255)
    LoanPackagerName = models.CharField(max_length=255)
    LoanPackagerStCd = models.CharField(max_length=255)
    LoanPackagerStrtName1 = models.CharField(max_length=255)
    LoanPackagerStrtName2 = models.CharField(max_length=255)
    LoanPackagerZip4Cd = models.CharField(max_length=255)
    LoanPackagerZipCd = models.CharField(max_length=255)
    LoanPackageSourcTypCd = models.CharField(max_length=255)
    LoanProjDelinquentInd = models.CharField(max_length=1)
    LoanProjectSizeCd = models.CharField(max_length=255)
    LoanProjGrossRcptRdcPrdAmt1 = models.CharField(max_length=255)
    LoanProjGrossRcptRdcPrdAmt2 = models.CharField(max_length=255)
    LoanScheduleCInd = models.CharField(max_length=1)
    LoanScheduleCYear = models.CharField(max_length=255)
    LoanTermAmortMnths = models.CharField(max_length=255)
    LoanTermMnths = models.PositiveIntegerField()
    LoanTermRevlMnths = models.CharField(max_length=255)
    LoanTermStartTypInd = models.CharField(max_length=255)
    LoanUsResidentInd = models.CharField(max_length=1)
    LowtoMediumIncomeInd = models.CharField(max_length=1)
    MnthsIntrstOnlyQty = models.PositiveIntegerField()
    NAICSCd = models.CharField(max_length=255)
    NetDebentrAmt = models.CharField(max_length=255)
    NetEarningsClause = models.CharField(max_length=255)
    NetExprtAmt = models.DecimalField(max_digits=10, decimal_places=2)
    NoteDt = models.CharField(max_length=255)
    OtherClosingCostAmt = models.CharField(max_length=255)
    OutPrgrmAreaOfOperInd = models.CharField(max_length=1)
    OverallPortfolioJobRatio = models.CharField(max_length=255)
    PayrollMnthlyAvgAmt = models.CharField(max_length=255)
    PPPLoanNumber = models.CharField(max_length=255)
    ProcessingFeeAmt = models.CharField(max_length=255)
    ProcessingMethodCd = models.CharField(max_length=255)
    ProjectCityName = models.CharField(max_length=255)
    ProjectStCd = models.CharField(max_length=255)
    ProjectStrtName1 = models.CharField(max_length=255)
    ProjectStrtName2 = models.CharField(max_length=255)
    ProjectZip4Cd = models.CharField(max_length=255)
    ProjectZipCd = models.CharField(max_length=255)
    PymtAmt = models.DecimalField(max_digits=10, decimal_places=2)
    PymtCeilingAndFloorCode = models.CharField(max_length=255)
    PymtCeilingMaxPct = models.CharField(max_length=255)
    PymtEscrowInd = models.CharField(max_length=1)
    PymtFloorMinPct = models.CharField(max_length=255)
    PymtFrequency = models.CharField(max_length=255)
    PymtIntOnlyDayOfMonth = models.CharField(max_length=255)
    PymtIntOnlyFreqCode = models.CharField(max_length=255)
    PymtIntOnlySkipMonths = models.CharField(max_length=255)
    PymtIntRateDeductionInd = models.CharField(max_length=1)
    PymtIntRateProgramOther = models.CharField(max_length=255)
    PymtLateChargeDays = models.CharField(max_length=255)
    PymtLateChargeInd = models.CharField(max_length=1)
    PymtLateChargePct = models.CharField(max_length=255)
    PymtNetEarnPrepayAmt = models.CharField(max_length=255)
    PymtNetEarnPrepayPct = models.CharField(max_length=255)
    PymtNetEarnRecaptureInd = models.CharField(max_length=1)
    PymtPrinAndIntDayOfMonth = models.CharField(max_length=255)
    PymtPrinAndIntSkipMonths = models.CharField(max_length=255)
    PymtSchedule = models.CharField(max_length=255)
    PymtTypeCode = models.CharField(max_length=255)
    ReconsiderationInd = models.CharField(max_length=1)
    RequestedAmt = models.DecimalField(max_digits=10, decimal_places=2)
    RevolvingInd = models.CharField(max_length=1)
    RuralUrbanInd = models.CharField(max_length=1)
    SBAGntyPct = models.DecimalField(max_digits=10, decimal_places=3)
    SeprateProcessFeeInd = models.CharField(max_length=1)
    StateLawComplianceForBulkInd = models.CharField(max_length=1)
    UnderwritingBy = models.CharField(max_length=255)
    UnderwrtrsFeeAmt = models.CharField(max_length=255)

    # Section: Borrower
    TaxId = models.CharField(max_length=10)
    BusinessPersonInd = models.CharField(max_length=1)
    ACHAccountNmb = models.CharField(max_length=255, null=True, blank=True)
    ACHAccountType = models.CharField(max_length=255, null=True, blank=True)
    ACHBnkNm = models.CharField(max_length=255, null=True, blank=True)
    ACHDepositorNm = models.CharField(max_length=255, null=True, blank=True)
    ACHRoutingNmb = models.CharField(max_length=255, null=True, blank=True)
    AlternateEmail = models.EmailField(max_length=255, null=True, blank=True)
    AlternatePhone = models.CharField(max_length=255, null=True, blank=True)
    BnkrptcyInd = models.CharField(max_length=1)
    BooksToLenderType = models.CharField(max_length=2, null=True, blank=True)
    BooksToLenderWithinDays = models.IntegerField(null=True, blank=True)
    BusDUNSNmb = models.CharField(max_length=9)
    BusinessName = models.CharField(max_length=255)
    BusOutstandingDebtInd = models.CharField(max_length=1, null=True, blank=True)
    BusPrimCntctNm = models.CharField(max_length=255, null=True, blank=True)
    ChkngAcctBalanceAmt = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    ControlInterestType = models.CharField(max_length=1)
    CrdScrFinAnnIntExp = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CrdScrFinCashAndEquiv = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CrdScrFinDDABal = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CrdScrFinEarnBefIntTx = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CrdScrFinNetWorth = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CrdScrFinTotAsset = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CrdScrFinTotLiab = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CrdScrFinTotSales = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    CreditReport = models.CharField(max_length=255, null=True, blank=True)
    CreditScore = models.CharField(max_length=255, null=True, blank=True)
    CreditScorSourcCd = models.CharField(max_length=255, null=True, blank=True)
    CurrBankName = models.CharField(max_length=255, null=True, blank=True)
    CurrOwnrshpEstblshDt = models.DateField(null=True, blank=True)
    EPCOperatingCompnyCd = models.CharField(max_length=255, null=True, blank=True)
    ExporterInd = models.CharField(max_length=1)
    ExtrnlCreditScorDt = models.DateField(null=True, blank=True)
    ExtrnlCreditScorInd = models.CharField(max_length=1)
    ExtrnlCreditScorNmb = models.CharField(max_length=255, null=True, blank=True)
    FedDisqualifiedInd = models.CharField(max_length=1)
    GamblingOrSexualNatureInd = models.CharField(max_length=1)
    InsurLiabInd = models.CharField(max_length=1)
    InsurLiabProductInd = models.CharField(max_length=1)
    InsurLiquorInd = models.CharField(max_length=1)
    InsurMalpracticeInd = models.CharField(max_length=1)
    InsurOtherDesc = models.CharField(max_length=255, null=True, blank=True)
    InsurOtherInd = models.CharField(max_length=1)
    InsurWorkersCompInd = models.CharField(max_length=1)
    LawsuitInd = models.CharField(max_length=1)
    LegalOrgnztnCd = models.CharField(max_length=1)
    MailCityName = models.CharField(max_length=255, null=True, blank=True)
    MailCountryCd = models.CharField(max_length=2)
    MailPostalCd = models.CharField(max_length=255, null=True, blank=True)
    MailStCd = models.CharField(max_length=2, null=True, blank=True)
    MailStNm = models.CharField(max_length=255, null=True, blank=True)
    MailStrtName1 = models.CharField(max_length=255, null=True, blank=True)
    MailStrtName2 = models.CharField(max_length=255, null=True, blank=True)
    MailZip4Cd = models.CharField(max_length=10, null=True, blank=True)
    MailZipCd = models.CharField(max_length=10, null=True, blank=True)
    NonFedEmpInd = models.CharField(max_length=1)
    NonFmrSBAEmpInd = models.CharField(max_length=1)
    NonGS13EmpInd = models.CharField(max_length=1)
    NonLegBrnchEmpInd = models.CharField(max_length=1)
    NonSBACEmpInd = models.CharField(max_length=1)
    PaymentsLessThanCCInd = models.CharField(max_length=1)
    PhysCityName = models.CharField(max_length=255)
    PhysCountryCd = models.CharField(max_length=2)
    PhysPostalCd = models.CharField(max_length=255, null=True, blank=True)
    PhysStCd = models.CharField(max_length=2)
    PhysStNm = models.CharField(max_length=255, null=True, blank=True)
    PhysStrtName1 = models.CharField(max_length=255)
    PhysStrtName2 = models.CharField(max_length=255, null=True, blank=True)
    PhysZip4Cd = models.CharField(max_length=10)
    PhysZipCd = models.CharField(max_length=10)
    PrevGovFinInd = models.CharField(max_length=1)
    PrimaryBusinessInd = models.CharField(max_length=1)
    PrimaryEmail = models.EmailField(max_length=255, null=True, blank=True)
    PrimaryPhone = models.CharField(max_length=10)
    PriorSBALoanInd = models.CharField(max_length=1)
    TaxIdCertInd = models.CharField(max_length=255, null=True, blank=True)
    TradeName = models.CharField(max_length=255, null=True, blank=True)

    # Section: Borrower Race
    RaceCd = models.CharField(max_length=1, null=True, blank=True)
    BorrowerRace_TaxId = models.CharField(max_length=10, null=True, blank=True)

    # Section: Comments
    CommntTxt = models.TextField(null=True, blank=True)

    # Section: CreditUnavailReasons
    CreditUnavailReasonCd = models.CharField(max_length=1, null=True, blank=True)
    CreditUnavailReasonCommnt = models.TextField(null=True, blank=True)

    # Section: DestinationCountries
    DestinationCountryCd = models.CharField(max_length=2, null=True, blank=True)

    # Section: Eligibility
    EligibleCd = models.CharField(max_length=3, null=True, blank=True)
    EligibleInd = models.CharField(max_length=1, null=True, blank=True)

    # Section: Interest
    Phase = models.CharField(max_length=1, null=True, blank=True)
    AdjustPeriodCd = models.CharField(max_length=255, null=True, blank=True)
    AdjustPeriodMnths = models.IntegerField(null=True, blank=True)
    BaseIntrstRatePct = models.DecimalField(max_digits=10, decimal_places=5, null=True, blank=True)
    BaseRateSourcTypCd = models.CharField(max_length=255, null=True, blank=True)
    BorrIntrstRatePct = models.DecimalField(max_digits=10, decimal_places=5, null=True, blank=True)
    FirstRateAdjustDt = models.DateField(null=True, blank=True)
    IntrstGuaranteeInd = models.CharField(max_length=1, null=True, blank=True)
    IntrstTypInd = models.CharField(max_length=1, null=True, blank=True)
    ShareOfTotalMnths = models.IntegerField(null=True, blank=True)
    ShareOfTotalPct = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True)

    # Section: PartnerInformation
    LocationId = models.IntegerField(null=True, blank=True)
    ACHAccountNmb = models.CharField(max_length=255, null=True, blank=True)
    ACHAccountType = models.CharField(max_length=255, null=True, blank=True)
    ACHRoutingNmb = models.CharField(max_length=255, null=True, blank=True)
    ACHTaxId = models.CharField(max_length=255, null=True, blank=True)

    # Section: Principal
    BusinessTaxId = models.CharField(max_length=10, null=True, blank=True)
    TaxId = models.CharField(max_length=10, null=True, blank=True)
    BusinessPersonInd = models.CharField(max_length=1, null=True, blank=True)
    AlienRgstrtnNmb = models.CharField(max_length=255, null=True, blank=True)
    AlternateEmail = models.EmailField(null=True, blank=True)
    AlternatePhone = models.CharField(max_length=20, null=True, blank=True)
    BirthCityName = models.CharField(max_length=255, null=True, blank=True)
    BirthCntryName = models.CharField(max_length=255, null=True, blank=True)
    BirthDt = models.DateField(null=True, blank=True)
    BirthStCd = models.CharField(max_length=2, null=True, blank=True)
    BnkrptcyInd = models.CharField(max_length=1, null=True, blank=True)
    BusDUNSNmb = models.CharField(max_length=9, null=True, blank=True)
    BusinessName = models.CharField(max_length=255, null=True, blank=True)
    ChkngAcctBalanceAmt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    CitznShipCntryName = models.CharField(max_length=255, null=True, blank=True)
    ControlInterestType = models.CharField(max_length=1, null=True, blank=True)
    ConvictdInd = models.CharField(max_length=1, null=True, blank=True)
    CreditReport = models.TextField(null=True, blank=True)
    CreditScore = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    CreditScorSourcCd = models.CharField(max_length=255, null=True, blank=True)
    CrmnlOffnsInd = models.CharField(max_length=1, null=True, blank=True)
    CSP60DayDelnqInd = models.CharField(max_length=1, null=True, blank=True)
    CurrBankName = models.CharField(max_length=255, null=True, blank=True)
    CurrOwnrshpEstblshDt = models.DateField(null=True, blank=True)
    EthnicCd = models.CharField(max_length=2, null=True, blank=True)
    ExporterInd = models.CharField(max_length=1, null=True, blank=True)
    ExtrnlCreditScorDt = models.DateField(null=True, blank=True)
    ExtrnlCreditScorInd = models.CharField(max_length=1, null=True, blank=True)
    ExtrnlCreditScorNmb = models.CharField(max_length=255, null=True, blank=True)
    FedDisqualifiedInd = models.CharField(max_length=1, null=True, blank=True)
    FedEmplyAffiltInd = models.CharField(max_length=1, null=True, blank=True)
    FirstName = models.CharField(max_length=255, null=True, blank=True)
    FngrprntWaivDt = models.DateField(null=True, blank=True)
    GndrCd = models.CharField(max_length=1, null=True, blank=True)
    GntyInd = models.CharField(max_length=1, null=True, blank=True)
    GntyLimitAmt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    GntyLimitCd = models.CharField(max_length=1, null=True, blank=True)
    GntyLimitCollatSeqNmb = models.CharField(max_length=255, null=True, blank=True)
    GntyLimitPct = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True)
    GntyLimitYrNmb = models.IntegerField(null=True, blank=True)
    GntyTypCd = models.CharField(max_length=1, null=True, blank=True)
    IndctPrleProbatnInd = models.CharField(max_length=1, null=True, blank=True)
    InsuranceAmt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    InsuranceDisabInd = models.CharField(max_length=1, null=True, blank=True)
    InsuranceLifeInd = models.CharField(max_length=1, null=True, blank=True)
    InsureDisabNames = models.CharField(max_length=255, null=True, blank=True)
    InsureName = models.CharField(max_length=255, null=True, blank=True)
    IntrstOthBusinessInd = models.CharField(max_length=1, null=True, blank=True)
    LastName = models.CharField(max_length=255, null=True, blank=True)
    LawsuitInd = models.CharField(max_length=1, null=True, blank=True)
    LegalOrgnztnCd = models.CharField(max_length=1, null=True, blank=True)
    LglActnInd = models.CharField(max_length=1, null=True, blank=True)
    LiquidCreditScore = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    MailCityName = models.CharField(max_length=255, null=True, blank=True)
    MailCountryCd = models.CharField(max_length=2, null=True, blank=True)
    MailPostalCd = models.CharField(max_length=255, null=True, blank=True)
    MailStCd = models.CharField(max_length=2, null=True, blank=True)
    MailStNm = models.CharField(max_length=255, null=True, blank=True)
    MailStrtName1 = models.CharField(max_length=255, null=True, blank=True)
    MailStrtName2 = models.CharField(max_length=255, null=True, blank=True)
    MailZip4Cd = models.CharField(max_length=255, null=True, blank=True)
    MailZipCd = models.CharField(max_length=255, null=True, blank=True)
    MiddleInitial = models.CharField(max_length=1, null=True, blank=True)
    NameSuffix = models.CharField(max_length=255, null=True, blank=True)
    NoNCACompetitorName = models.CharField(max_length=255, null=True, blank=True)
    NoNCAInd = models.CharField(max_length=1, null=True, blank=True)
    OwnrshpInBusinessPct = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    PhysCityName = models.CharField(max_length=255, null=True, blank=True)
    PhysCountryCd = models.CharField(max_length=2, null=True, blank=True)
    PhysPostalCd = models.CharField(max_length=255, null=True, blank=True)
    PhysStCd = models.CharField(max_length=2, null=True, blank=True)
    PhysStNm = models.CharField(max_length=255, null=True, blank=True)
    PhysStrtName1 = models.CharField(max_length=255, null=True, blank=True)
    PhysStrtName2 = models.CharField(max_length=255, null=True, blank=True)
    PhysZip4Cd = models.CharField(max_length=255, null=True, blank=True)
    PhysZipCd = models.CharField(max_length=255, null=True, blank=True)
    PrimaryEmail = models.EmailField(null=True, blank=True)
    PrimaryPhone = models.CharField(max_length=20, null=True, blank=True)
    PrimBusExprnceYrNmb = models.IntegerField(null=True, blank=True)
    PriorSBALoanInd = models.CharField(max_length=1, null=True, blank=True)
    TaxIdCertInd = models.CharField(max_length=1, null=True, blank=True)
    Title = models.CharField(max_length=255, null=True, blank=True)
    TradeName = models.CharField(max_length=255, null=True, blank=True)
    USCitznInd = models.CharField(max_length=2, null=True, blank=True)
    VetCd = models.CharField(max_length=1, null=True, blank=True)
    VetCertInd = models.CharField(max_length=1, null=True, blank=True)

    # Section: PrincipalRace
    TaxId = models.CharField(max_length=10, null=True, blank=True)
    BusinessPersonInd = models.CharField(max_length=1, null=True, blank=True)
    RaceCd = models.CharField(max_length=1, null=True, blank=True)

    # Section: SpecialPurpose
    SpcPurpsLoanCd = models.CharField(max_length=4, null=True, blank=True)

    # Section: UseOfProceeds
    ProceedTypCd = models.CharField(max_length=2, null=True, blank=True)
    LoanProceedTypCd = models.CharField(max_length=2, null=True, blank=True)
    ProceedAmt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    ProceedOthTypTxt = models.CharField(max_length=255, null=True, blank=True)
    PurchaseAgrmtDt = models.DateField(null=True, blank=True)
    PurchaseAgrmtNCAInd = models.CharField(max_length=1, null=True, blank=True)
    PurchaseIntngblAssetAmt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    PurchaseIntngblAssetDescTxt = models.CharField(max_length=255, null=True, blank=True)
    RefDescTxt = models.CharField(max_length=255, null=True, blank=True)
    StockholderName = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.LoanName

    class Meta:
        db_table = 'SBA_7a_Application'