# Generated by Django 4.1.8 on 2023-04-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_type',
            field=models.CharField(choices=[('INTEREST_ONLY', 'Interest Only'), ('PRINCIPAL_AND_INTEREST', 'Principal and Interest'), ('MODIFIED', 'Modified')], max_length=22),
        ),
    ]
